# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/comparch/Lab/Lab3/single_cycle_cpu/single_cycle_cpu.cache/wt [current_project]
set_property parent.project_path /home/comparch/Lab/Lab3/single_cycle_cpu/single_cycle_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo /home/comparch/Lab/Lab3/single_cycle_cpu/single_cycle_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /home/comparch/Lab/Lab3/verilog/adder_1bit.v
  /home/comparch/Lab/Lab3/verilog/alu.v
  /home/comparch/Lab/Lab3/verilog/decoders.v
  /home/comparch/Lab/Lab3/verilog/dff.v
  /home/comparch/Lab/Lab3/verilog/instructionDecoder.v
  /home/comparch/Lab/Lab3/verilog/lshift2.v
  /home/comparch/Lab/Lab3/verilog/memory.v
  /home/comparch/Lab/Lab3/verilog/mux.v
  /home/comparch/Lab/Lab3/verilog/regfile.v
  /home/comparch/Lab/Lab3/verilog/register.v
  /home/comparch/Lab/Lab3/verilog/signextend.v
}
set_property file_type "Verilog Header" [get_files /home/comparch/Lab/Lab3/verilog/adder_1bit.v]
set_property file_type "Verilog Header" [get_files /home/comparch/Lab/Lab3/verilog/alu.v]
set_property file_type "Verilog Header" [get_files /home/comparch/Lab/Lab3/verilog/decoders.v]
set_property file_type "Verilog Header" [get_files /home/comparch/Lab/Lab3/verilog/dff.v]
set_property file_type "Verilog Header" [get_files /home/comparch/Lab/Lab3/verilog/instructionDecoder.v]
set_property file_type "Verilog Header" [get_files /home/comparch/Lab/Lab3/verilog/lshift2.v]
set_property file_type "Verilog Header" [get_files /home/comparch/Lab/Lab3/verilog/memory.v]
set_property file_type "Verilog Header" [get_files /home/comparch/Lab/Lab3/verilog/mux.v]
set_property file_type "Verilog Header" [get_files /home/comparch/Lab/Lab3/verilog/regfile.v]
set_property file_type "Verilog Header" [get_files /home/comparch/Lab/Lab3/verilog/register.v]
set_property file_type "Verilog Header" [get_files /home/comparch/Lab/Lab3/verilog/signextend.v]
read_verilog -library xil_defaultlib /home/comparch/Lab/Lab3/single_cycle_cpu/single_cycle_cpu.srcs/sources_1/imports/verilog/cpu.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/comparch/Lab/Lab3/single_cycle_cpu/single_cycle_cpu.srcs/constrs_1/imports/comparch/ZYBO_Master.xdc
set_property used_in_implementation false [get_files /home/comparch/Lab/Lab3/single_cycle_cpu/single_cycle_cpu.srcs/constrs_1/imports/comparch/ZYBO_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top cpu -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
